<img src="https://github.com/radevicstefan-afk/intro-to-eda-and-pandas/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# EDA with `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a data set at a high level with `pandas`.

### Notebook Guide
- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Exporting data
- Conclusions and Takeaways

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

This notebook will showcase some fundamental `pandas` features and commands and in notebook 3, you will answer some questions about the data, and therefore the business question, on your own.

## Loading a CSV into a `DataFrame`

Use this link to read the CSV file:
https://raw.githubusercontent.com/juanatga/intro-to-eda-and-pandas/main/data/lego.csv

In [3]:
import pandas
import pandas as pd

In [4]:
url = 'https://raw.githubusercontent.com/juanatga/intro-to-eda-and-pandas/main/data/lego.csv'

In [5]:
pd.read_csv(url)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,88.0,0.0,5.99,NaN,NaN
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,107.0,0.0,5.99,NaN,NaN

In [6]:
df_lego = pd.read_csv(url)

We'll read in the data. The `read_csv` method has lots of options, but the defaults are usually a good place to start.

In [7]:
df_lego.shape

(14936, 17)

In [8]:
df_lego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Packaging         14936 non-null  object
 8   Num_Instructions  14936 non-null  int64
 9   Availability      14936 non-null  object
 10  Pieces            13133 non-null  float64
 11  Minifigures       7686 non-null   float64
 12  Owned             14771 non-null  float64
 13  Rating            14936 non-null  float64
 14  USD_MSRP          5837 non-null   float64
 15  Total_Quantity    12276 non-null  float64
 16  Current_Price     5442 non-null   float64
dtypes: float64(7), int64(2), object(8)
memory usage: 1.9+ MB

Let's look at the data!

In [9]:
df_lego.head(6)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN
5,133-1,Locomotive,1975,Trains,Modern day,4.5/12V,Normal,{Not specified},0,{Not specified},87.0,NaN,279.0,0.0,NaN,0.0,NaN

In [10]:
#Drop is used to delete columns fro the df_lego
clean_data = df_lego.drop(columns=["Packaging"])
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Num_Instructions  14936 non-null  int64
 8   Availability      14936 non-null  object
 9   Pieces            13133 non-null  float64
 10  Minifigures       7686 non-null   float64
 11  Owned             14771 non-null  float64
 12  Rating            14936 non-null  float64
 13  USD_MSRP          5837 non-null   float64
 14  Total_Quantity    12276 non-null  float64
 15  Current_Price     5442 non-null   float64
dtypes: float64(7), int64(2), object(7)
memory usage: 1.8+ MB

In [ ]:
df_lego.drop(columns=["Owned"], inplace=True)
df_lego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Num_Instructions  14936 non-null  int64
 8   Availability      14936 non-null  object
 9   Pieces            13133 non-null  float64
 10  Minifigures       7686 non-null   float64
 11  Rating            14936 non-null  float64
 12  USD_MSRP          5837 non-null   float64
 13  Total_Quantity    12276 non-null  float64
 14  Current_Price     5442 non-null   float64
dtypes: float64(6), int64(2), object(7)
memory usage: 1.7+ MB

In [11]:
df_lego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Packaging         14936 non-null  object
 8   Num_Instructions  14936 non-null  int64
 9   Availability      14936 non-null  object
 10  Pieces            13133 non-null  float64
 11  Minifigures       7686 non-null   float64
 12  Owned             14771 non-null  float64
 13  Rating            14936 non-null  float64
 14  USD_MSRP          5837 non-null   float64
 15  Total_Quantity    12276 non-null  float64
 16  Current_Price     5442 non-null   float64
dtypes: float64(7), int64(2), object(8)
memory usage: 1.9+ MB

In [12]:
#BACK TO YOU
#Delete the following columns ["Rating","Pieces"]

df_lego.drop(columns=["Rating", "Pieces"], inplace=True)

In [13]:
df_lego.head()

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,10.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,11.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,10.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,8.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},NaN,10.0,NaN,0.0,NaN

In [14]:
df_lego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Packaging         14936 non-null  object
 8   Num_Instructions  14936 non-null  int64
 9   Availability      14936 non-null  object
 10  Minifigures       7686 non-null   float64
 11  Owned             14771 non-null  float64
 12  USD_MSRP          5837 non-null   float64
 13  Total_Quantity    12276 non-null  float64
 14  Current_Price     5442 non-null   float64
dtypes: float64(5), int64(2), object(8)
memory usage: 1.7+ MB

In [ ]:
#Goal: remove the column "Minifigures"
#Option 1: inplace=False

df_lego.drop(columns=["Minifigures"]) #Same as inplace=False

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Num_Instructions,Availability,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,0,{Not specified},NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,0,{Not specified},NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,0,{Not specified},NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,0,{Not specified},NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,0,{Not specified},NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,0,LEGO exclusive,5.99,NaN,NaN
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,0,LEGO exclusive,5.99,NaN,NaN
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,0,LEGO exclusive,5.99,NaN,NaN
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,0,LEGO exclusive,5.99,NaN,NaN
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,0,LEGO exclusive,5.99,NaN,NaN

In [ ]:
df_lego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Num_Instructions  14936 non-null  int64
 8   Availability      14936 non-null  object
 9   Minifigures       7686 non-null   float64
 10  USD_MSRP          5837 non-null   float64
 11  Total_Quantity    12276 non-null  float64
 12  Current_Price     5442 non-null   float64
dtypes: float64(4), int64(2), object(7)
memory usage: 1.5+ MB

In [ ]:
#Option 2: Using inplace = True
#Why do I want to do this?

df_lego.drop(columns=["Minifigures"], inplace=True)

In [ ]:
df_lego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Num_Instructions  14936 non-null  int64
 8   Availability      14936 non-null  object
 9   USD_MSRP          5837 non-null   float64
 10  Total_Quantity    12276 non-null  float64
 11  Current_Price     5442 non-null   float64
dtypes: float64(3), int64(2), object(7)
memory usage: 1.4+ MB

# Column Operations
---

There are some columns we don't need, such as how many users on a specific platform claim to own each set. Let's remove the "Owned" column.

OK let's take a look at the data again

What?! The `Owned` column is still there, but we saw it disappear above!

This is because `pandas` operations almost always return a **copy** of the data without changing the underlying data set.

To make an operation permanent, you need to explicitly overwrite your `DataFrame` object:

Let's limit our data to only the most recent sets, say the last 10 years.

To do this we will:

- calculate the age of each set
- filter out anything older than 10 years

To create new columns, we can perform a vectorized operation on the entire column (not loop through its values):

In [15]:
df_lego["Year"]

0        1975
1        1975
2        1975
3        1975
4        1975
         ...
14931    2023
14932    2023
14933    2023
14934    2023
14935    2023
Name: Year, Length: 14936, dtype: int64

In [16]:
current_year = 2026

In [17]:
Age = current_year - df_lego["Year"]
Age

0        51
1        51
2        51
3        51
4        51
         ..
14931     3
14932     3
14933     3
14934     3
14935     3
Name: Year, Length: 14936, dtype: int64

In [18]:
import datetime
current_year = datetime.datetime.today().year
current_year

2026

In [19]:
df_lego["Age"] = current_year - df_lego["Year"]
df_lego["Age"]

0        51
1        51
2        51
3        51
4        51
         ..
14931     3
14932     3
14933     3
14934     3
14935     3
Name: Age, Length: 14936, dtype: int64

In [20]:
df_lego["Age"] < 10

0        False
1        False
2        False
3        False
4        False
         ...
14931     True
14932     True
14933     True
14934     True
14935     True
Name: Age, Length: 14936, dtype: bool

In [22]:
df_lego.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Packaging         14936 non-null  object
 8   Num_Instructions  14936 non-null  int64
 9   Availability      14936 non-null  object
 10  Minifigures       7686 non-null   float64
 11  Owned             14771 non-null  float64
 12  USD_MSRP          5837 non-null   float64
 13  Total_Quantity    12276 non-null  float64
 14  Current_Price     5442 non-null   float64
 15  Age               14936 non-null  int64
dtypes: float64(5), int64(3), object(8)
memory usage: 1.8+ MB

In [31]:
lego_df = df_lego

In [32]:
df_lego[["Age", "Year"]]

       Age  Year
0       51  1975
1       51  1975
2       51  1975
3       51  1975
4       51  1975
...    ...   ...
14931    3  2023
14932    3  2023
14933    3  2023
14934    3  2023
14935    3  2023

[14936 rows x 2 columns]

In [33]:
age_filter = df_lego["Age"] <10

In [34]:
df_lego[age_filter]

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price,Age
11436,10255-1,Assembly Square,2017,Creator Expert,Model making,Modular Buildings Collection,Normal,Box,2,LEGO exclusive,9.0,26028.0,299.99,20.0,299.9500,9
11437,10256-1,Taj Mahal,2017,Creator Expert,Model making,Landmarks,Normal,Box,2,LEGO exclusive,NaN,4384.0,369.99,3.0,404.9910,9
11438,10257-1,Carousel,2017,Creator Expert,Model making,Fairground Collection,Normal,Box,2,LEGO exclusive,7.0,8752.0,199.99,12.0,440.0000,9
11439,10258-1,London Bus,2017,Creator Expert,Model making,Vehicles,Normal,Box,2,LEGO exclusive,NaN,12204.0,139.99,12.0,121.4910,9
11440,10259-1,Winter Village Station,2017,Creator Expert,Model making,Winter Village Collection,Normal,Box,4,LEGO exclusive,5.0,12718.0,79.99,27.0,203.6194,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,88.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,107.0,5.99,NaN,NaN,3

In [35]:
df_lego[df_lego["Age"] <10]

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price,Age
11436,10255-1,Assembly Square,2017,Creator Expert,Model making,Modular Buildings Collection,Normal,Box,2,LEGO exclusive,9.0,26028.0,299.99,20.0,299.9500,9
11437,10256-1,Taj Mahal,2017,Creator Expert,Model making,Landmarks,Normal,Box,2,LEGO exclusive,NaN,4384.0,369.99,3.0,404.9910,9
11438,10257-1,Carousel,2017,Creator Expert,Model making,Fairground Collection,Normal,Box,2,LEGO exclusive,7.0,8752.0,199.99,12.0,440.0000,9
11439,10258-1,London Bus,2017,Creator Expert,Model making,Vehicles,Normal,Box,2,LEGO exclusive,NaN,12204.0,139.99,12.0,121.4910,9
11440,10259-1,Winter Village Station,2017,Creator Expert,Model making,Winter Village Collection,Normal,Box,4,LEGO exclusive,5.0,12718.0,79.99,27.0,203.6194,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,88.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,107.0,5.99,NaN,NaN,3

In [46]:
df_lego_filter = df_lego[df_lego["Age"] <10]
df_lego_filter

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price,Age
11436,10255-1,Assembly Square,2017,Creator Expert,Model making,Modular Buildings Collection,Normal,Box,2,LEGO exclusive,9.0,26028.0,299.99,20.0,299.9500,9
11437,10256-1,Taj Mahal,2017,Creator Expert,Model making,Landmarks,Normal,Box,2,LEGO exclusive,NaN,4384.0,369.99,3.0,404.9910,9
11438,10257-1,Carousel,2017,Creator Expert,Model making,Fairground Collection,Normal,Box,2,LEGO exclusive,7.0,8752.0,199.99,12.0,440.0000,9
11439,10258-1,London Bus,2017,Creator Expert,Model making,Vehicles,Normal,Box,2,LEGO exclusive,NaN,12204.0,139.99,12.0,121.4910,9
11440,10259-1,Winter Village Station,2017,Creator Expert,Model making,Winter Village Collection,Normal,Box,4,LEGO exclusive,5.0,12718.0,79.99,27.0,203.6194,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,88.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,107.0,5.99,NaN,NaN,3

In [47]:
lego_df_filter = df_lego_filter
lego_df_filter

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price,Age
11436,10255-1,Assembly Square,2017,Creator Expert,Model making,Modular Buildings Collection,Normal,Box,2,LEGO exclusive,9.0,26028.0,299.99,20.0,299.9500,9
11437,10256-1,Taj Mahal,2017,Creator Expert,Model making,Landmarks,Normal,Box,2,LEGO exclusive,NaN,4384.0,369.99,3.0,404.9910,9
11438,10257-1,Carousel,2017,Creator Expert,Model making,Fairground Collection,Normal,Box,2,LEGO exclusive,7.0,8752.0,199.99,12.0,440.0000,9
11439,10258-1,London Bus,2017,Creator Expert,Model making,Vehicles,Normal,Box,2,LEGO exclusive,NaN,12204.0,139.99,12.0,121.4910,9
11440,10259-1,Winter Village Station,2017,Creator Expert,Model making,Winter Village Collection,Normal,Box,4,LEGO exclusive,5.0,12718.0,79.99,27.0,203.6194,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,88.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,107.0,5.99,NaN,NaN,3

To create a new column, we use syntax similar to adding a key to a dictionary

In [ ]:
lego_df_minors = df_lego[df_lego["Age"] <10]
lego_df_minors

#### Reflection

How is this different from working with Python types, like numbers or lists?

---

When we look at the data, our new column will be at the end

We can select multiple columns to verify the new age column. To do this, pass a list instead of a single column name.

# Filtering
---

Now, we can use our new column to find only the newest sets.

To filter a `DataFrame` we need:

1. A filter to apply (like a `WHERE` clause in SQL)
2. To apply this filter to the `DataFrame`

With `pandas`, even boolean operations are vectorized!

We can save that filter into a variable, then use it to index the `DataFrame`

We can also combine those steps (you'll see this a lot)

We could also save this filtered version into a new `DataFrame` variable

This is a copy, so changes to this `DataFrame` **do not affect the original `DataFrame`** but if we tried to make any changes to it we'll get a warning

This warning is just a reminder that:

- `filtered` is a "slice" of the original `lego` `DataFrame`
- it is a **copy**, so any changes to `filtered` **will not affect** `lego`

To make this go away, you can be explicit about the fact that we are copying data:

No warning!

### Multiple Filters

What about only looking at new sets that have a Star Wars theme?

To combine multiple filters:

1. Each filter needs to be parenthesized
2. Instead of Python's `and` we use `&` and instead of `or` we use `|`

In [65]:
lego_df[(lego_df["Age"] < 10) | (lego_df["Theme"] == "Star Wars")]

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price,Age
3541,7101-1,Lightsaber Duel,1999,Star Wars,Licensed,Episode I,Normal,Box,1,Retail,2.0,10759.0,NaN,9.0,85.00,27
3542,7110-1,Landspeeder,1999,Star Wars,Licensed,Episode IV,Normal,Box,1,Retail,2.0,12190.0,NaN,7.0,75.00,27
3543,7111-1,Droid Fighter,1999,Star Wars,Licensed,Episode I,Normal,Box,1,Retail,NaN,10407.0,NaN,6.0,30.00,27
3544,7121-1,Naboo Swamp,1999,Star Wars,Licensed,Episode I,Normal,Box,1,Retail,4.0,9568.0,NaN,9.0,45.00,27
3545,7128-1,Speeder Bikes,1999,Star Wars,Licensed,Episode VI,Normal,Box,1,Retail,3.0,11657.0,NaN,2.0,128.25,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,88.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,107.0,5.99,NaN,NaN,3

# Sorting
---

Let's find the most expensive LEGO sets. To do this, we need to sort our data.

Sorting is done by calling `.sort_values()` on the `DataFrame` and specifying the column.

In [50]:
lego_df.sort_values("Age")

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price,Age
14927,854234-1,Chili Girl Key Chain,2023,Gear,Miscellaneous,Key Chains/Minifigures,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14926,682304-1,Green Goblin,2023,Marvel Super Heroes,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,1.0,132.0,NaN,0.0,NaN,3
14925,682303-1,Miles Morales,2023,Marvel Super Heroes,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,1.0,563.0,NaN,2.0,6.95,3
14924,662309-1,Knight with Chest and Anvil,2023,Minecraft,Licensed,Magazine Gift,Other,Foil pack,0,Retail - limited,1.0,261.0,NaN,0.0,NaN,3
14923,662303-1,Adventurer with Drowned and Axolotl,2023,Minecraft,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,NaN,54.0,NaN,0.0,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,133-1,Locomotive,1975,Trains,Modern day,4.5/12V,Normal,{Not specified},0,{Not specified},NaN,279.0,NaN,0.0,NaN,51
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},NaN,10.0,NaN,0.0,NaN,51
30,518-8,Bricks and half bricks and trolley,1975,Duplo,Pre-school,NaN,Normal,Box,0,Retail,NaN,24.0,NaN,0.0,NaN,51
31,519-8,Bricks and half bricks and arches and trolley,1975,Duplo,Pre-school,NaN,Normal,Box,0,Retail,NaN,21.0,NaN,0.0,NaN,51
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,11.0,NaN,NaN,NaN,51

The default is ascending order, so to sort in descending order we specify `ascending=False`

In [52]:
ascending = False
lego_df.sort_values("Age")

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price,Age
14927,854234-1,Chili Girl Key Chain,2023,Gear,Miscellaneous,Key Chains/Minifigures,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14926,682304-1,Green Goblin,2023,Marvel Super Heroes,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,1.0,132.0,NaN,0.0,NaN,3
14925,682303-1,Miles Morales,2023,Marvel Super Heroes,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,1.0,563.0,NaN,2.0,6.95,3
14924,662309-1,Knight with Chest and Anvil,2023,Minecraft,Licensed,Magazine Gift,Other,Foil pack,0,Retail - limited,1.0,261.0,NaN,0.0,NaN,3
14923,662303-1,Adventurer with Drowned and Axolotl,2023,Minecraft,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,NaN,54.0,NaN,0.0,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,133-1,Locomotive,1975,Trains,Modern day,4.5/12V,Normal,{Not specified},0,{Not specified},NaN,279.0,NaN,0.0,NaN,51
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},NaN,10.0,NaN,0.0,NaN,51
30,518-8,Bricks and half bricks and trolley,1975,Duplo,Pre-school,NaN,Normal,Box,0,Retail,NaN,24.0,NaN,0.0,NaN,51
31,519-8,Bricks and half bricks and arches and trolley,1975,Duplo,Pre-school,NaN,Normal,Box,0,Retail,NaN,21.0,NaN,0.0,NaN,51
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,11.0,NaN,NaN,NaN,51

# Exporting data
---

For now, we will report to our stakeholders that Star Wars sets seem to command high prices. We will export the most recent Star Wars sets to a separate `DataFrame`

`pandas` also supports many *export* formats, like CSVs

In [66]:
lego_df.to_csv("star_wars.csv", index = False)

pd.read_csv("star_wars.csv")

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Minifigures,Owned,USD_MSRP,Total_Quantity,Current_Price,Age
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,10.0,NaN,NaN,NaN,51
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,11.0,NaN,NaN,NaN,51
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,10.0,NaN,0.0,NaN,51
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},NaN,8.0,NaN,NaN,NaN,51
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},NaN,10.0,NaN,0.0,NaN,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,2.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,88.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,107.0,5.99,NaN,NaN,3

# Conclusions and Takeaways
---

- `pandas` is the most popular data analysis library in the Python ecosystem
- `pandas` introduces the `Series` and `DataFrame` types to make manipulating data easier
- `pandas` uses vectorized operations to manipulate entire columns at once
- most operations return *copies* of the data, so users must be explicit when overwriting their data

#### Reflect

Make sure you understand:

- why working with `pandas` is more efficient than working with Python objects like lists
- what the difference between a `DataFrame` and a `Series` is
- that most of the time `pandas` operations return **copies** of the data